import { useMemo, useRef } from 'react'
import { useVirtualizer } from '@tanstack/react-virtual'
import { Search, Trash2 } from 'lucide-react'
import { toast } from 'sonner'
import { api, errorMessage } from '@/api/client'
import { Button } from '@/components/ui/Button'
import { useLive } from '@/live/store'
import type { Journey } from '@/live/traffic'
import { cn } from '@/lib/cn'
import { RequestDetail } from './RequestDetail'
import { statusTone } from './journey'
import { useTrafficUI, type TrafficFilter } from './store'

const FILTERS: { value: TrafficFilter; label: string }[] = [
  { value: 'all', label: 'All' },
  { value: 'errors', label: 'Errors' },
  { value: 'redirects', label: 'Redirects' },
  { value: 'generated', label: 'Generated by a function' },
]

const matches = (j: Journey, filter: TrafficFilter, search: string) => {
  const status = j.status ?? 0
  if (filter === 'errors' && !(status >= 400 || j.failure)) return false
  if (filter === 'redirects' && !(status >= 300 && status < 400)) return false
  if (filter === 'generated' && !j.stages.some(s => s.stage?.kind === 'short-circuit')) return false
  if (!search) return true
  const q = search.toLowerCase()
  return (j.url ?? '').toLowerCase().includes(q) || String(j.status ?? '').startsWith(q) || (j.method ?? '').toLowerCase() === q
}

const ROW = 30
const time = (iso: string) => new Date(iso).toLocaleTimeString(undefined, { hour12: false })

/** Live traffic: every request through the distribution, filterable, with its journey on selection. */
export function TrafficPanel() {
  const traffic = useLive(s => s.traffic)
  const clear = useLive(s => s.clearTraffic)
  const { selectedId, filter, search, select, setFilter, setSearch } = useTrafficUI()
  const rows = useMemo(() => traffic.order.map(id => traffic.byId[id]).filter(j => matches(j, filter, search.trim())), [traffic, filter, search])
  const selected = selectedId ? traffic.byId[selectedId] : undefined
  const scroller = useRef<HTMLDivElement>(null)
  // TanStack Virtual returns functions the React compiler mustn't memoize; this component opts out of it
  // eslint-disable-next-line react-hooks/incompatible-library
  const virtual = useVirtualizer({ count: rows.length, getScrollElement: () => scroller.current, estimateSize: () => ROW, overscan: 12,
    // Rows render before the list is measured (first paint, and environments without layout)
    initialRect: { width: 800, height: ROW * 20 } })

  const onClear = async () => {
    try {
      await api('DELETE', '/requests')
      clear()
      select(null)
    } catch (err) {
      toast.error(errorMessage(err))
    }
  }

  return (
    <section id="traffic" aria-labelledby="traffic-title" className="flex min-h-0 flex-1 flex-col border-t border-line bg-surface">
      <div className="flex flex-wrap items-center gap-2 border-b border-line px-3 py-1.5">
        <h2 id="traffic-title" className="text-xs font-semibold uppercase tracking-wide text-muted">
          Traffic <span className="font-normal normal-case">({traffic.order.length})</span>
        </h2>
        <div role="group" aria-label="Filter" className="flex gap-1">
          {FILTERS.map(f => (
            <button key={f.value} type="button" aria-pressed={filter === f.value} onClick={() => setFilter(f.value)}
              className={cn('rounded border px-2 py-0.5 text-xs', filter === f.value ? 'border-accent text-accent' : 'border-line text-muted hover:text-text')}>
              {f.label}
            </button>
          ))}
        </div>
        <label className="relative ml-auto">
          <span className="sr-only">Search requests</span>
          <Search size={13} className="pointer-events-none absolute left-2 top-1/2 -translate-y-1/2 text-muted" aria-hidden />
          <input type="search" value={search} onChange={e => setSearch(e.target.value)} placeholder="Path, status or method"
            className="h-7 w-56 rounded border border-line bg-bg pl-7 pr-2 text-xs" />
        </label>
        <Button size="sm" variant="ghost" onClick={onClear} disabled={traffic.order.length === 0}><Trash2 size={13} /> Clear</Button>
      </div>

      <div className={cn('grid min-h-0 flex-1', selected ? 'grid-cols-[minmax(0,2fr)_minmax(0,3fr)]' : 'grid-cols-1')}>
        <div ref={scroller} className="min-h-0 overflow-y-auto focus:outline-none focus-visible:ring-2 focus-visible:ring-accent" role="listbox" aria-label="Requests"
          tabIndex={0} aria-activedescendant={selectedId ? `req-${selectedId}` : undefined}
          onKeyDown={e => {
            // Up and down move through the requests, keeping the selection in view
            if (e.key !== 'ArrowDown' && e.key !== 'ArrowUp') return
            e.preventDefault()
            const at = rows.findIndex(r => r.id === selectedId)
            const next = Math.max(0, Math.min(rows.length - 1, at + (e.key === 'ArrowDown' ? 1 : -1)))
            if (rows[next]) { select(rows[next].id); virtual.scrollToIndex(next) }
          }}>
          {rows.length === 0 && (
            <p className="p-4 text-sm text-muted">{traffic.order.length === 0 ? 'Requests to the distribution appear here as they happen. Send one from the Viewer.' : 'No request matches.'}</p>
          )}
          <div style={{ height: virtual.getTotalSize(), position: 'relative' }}>
            {virtual.getVirtualItems().map(item => {
              const j = rows[item.index]
              const fns = new Set(j.stages.flatMap(s => (s.stage && 'functionIds' in s.stage ? s.stage.functionIds : []))).size
              return (
                <div key={j.id} id={`req-${j.id}`} role="option" aria-selected={j.id === selectedId} tabIndex={-1}
                  onClick={() => select(j.id === selectedId ? null : j.id)}
                  style={{ position: 'absolute', top: 0, left: 0, right: 0, height: ROW, transform: `translateY(${item.start}px)` }}
                  className={cn('flex cursor-pointer items-center gap-3 border-b border-line/60 px-3 text-xs', j.id === selectedId ? 'bg-surface-2' : 'hover:bg-surface-2')}>
                  <span className={cn('w-9 font-mono font-semibold', statusTone(j.status, !!j.failure))}>{j.status ?? '…'}</span>
                  <span className="w-12 font-mono text-muted">{j.method}</span>
                  <span className="min-w-0 flex-1 truncate font-mono">{j.url}</span>
                  {fns > 0 && <span className="text-accent" title={`${fns} function${fns === 1 ? '' : 's'} ran`}>ƒ{fns}</span>}
                  <span className="w-14 text-right font-mono text-muted">{j.durationMs != null ? `${j.durationMs} ms` : ''}</span>
                  <span className="hidden w-16 text-right font-mono text-muted md:inline">{time(j.time)}</span>
                </div>
              )
            })}
          </div>
        </div>
        {selected && <div className="min-h-0 border-l border-line"><RequestDetail key={selected.id} journey={selected} /></div>}
      </div>
    </section>
  )
}
