/**
 * AWS Lambda@Edge Limits
 *
 * Source: CloudFront Developer Guide — "Quotas on Lambda@Edge" and
 * "Restrictions on Lambda@Edge › Restrictions on the request body with the include body option".
 */
export const AWS_LIMITS = {
    // Request body exposed to the function: truncated (inputTruncated: true), never rejected
    VIEWER_REQUEST_BODY_BYTES: 40 * 1024,              // 40 KB (viewer request)
    LE_BODY_INPUT_CAP_BYTES: 1024 * 1024,             // 1 MB (origin request)
    // Request body a function returns with action 'replace' (exceeding it is a 502 validation error)
    VIEWER_REPLACED_BODY_TEXT_BYTES: 40 * 1024,        // 40 KB
    VIEWER_REPLACED_BODY_BASE64_BYTES: Math.floor(53.2 * 1024), // 53.2 KB
    ORIGIN_REPLACED_BODY_TEXT_BYTES: 1024 * 1024,      // 1 MB
    ORIGIN_REPLACED_BODY_BASE64_BYTES: Math.floor(1.33 * 1024 * 1024), // 1.33 MB
    // Size of a response generated by a function, including headers and body
    VIEWER_GENERATED_RESPONSE_BYTES: 40 * 1024,        // 40 KB (viewer request/response)
    GENERATED_RESPONSE_BODY_BYTES: 1024 * 1024,        // 1 MB (origin request/response)
    TRAFFIC_BODY_SNAPSHOT_BYTES: 1024 * 1024,          // 1MB (Forensic snapshot/WebUI cap)
    COMPRESSION_BYPASS_BYTES: 10 * 1024 * 1024,        // 10MB
    // AWS function timeout (30 seconds for all event types). Reference limit: exceeding it only WARNS,
    // because local hardware and networks aren't AWS's.
    VIEWER_TIMEOUT_MS: 30000,
    ORIGIN_TIMEOUT_MS: 30000,
    // Enforced limit with leeway (emulator-only): a handler still unsettled here is runaway code
    // and fails with 503 LambdaLimitExceeded, so it can't hang the request.
    VIEWER_TIMEOUT_GUARD_MS: 60000,
    ORIGIN_TIMEOUT_GUARD_MS: 60000
} as const;

/**
 * AWS CloudFront Function (CFF) Strict Execution Limits
 */
export const CFF_LIMITS = {
    MAX_CODE_SIZE_BYTES: 10 * 1024,           // 10 KB (Quotas on CloudFront Functions; not adjustable)
    MAX_CPU_TIME_MS: 1,                       // Reference limit: 1ms warning (AWS measures compute utilization)
    RUNAWAY_GUARD_MS: 1000                    // Enforced limit with leeway (emulator-only): stops infinite loops
} as const;

/**
 * AWS Forbidden & Read-only Headers
 */
export const AWS_HEADERS = {
    /**
     * Disallowed: not exposed to edge functions, and functions can't add them (502 if they do).
     * Source: "Restrictions on all edge functions › Disallowed headers".
     */
    DISALLOWED: [
        'connection', 'expect', 'keep-alive', 'proxy-authenticate', 'proxy-authorization',
        'proxy-connection', 'trailer', 'upgrade', 'x-accel-buffering', 'x-accel-charset',
        'x-accel-limit-rate', 'x-accel-redirect', 'x-amzn-auth', 'x-amzn-cf-billing',
        'x-amzn-cf-id', 'x-amzn-cf-xff', 'x-amzn-errortype', 'x-amzn-fle-profile',
        'x-amzn-header-count', 'x-amzn-header-order', 'x-amzn-lambda-integration-tag',
        'x-amzn-requestid', 'x-cache', 'x-forwarded-proto', 'x-real-ip',
        'cloudfront-viewer-cert-pem', 'client-cert', 'client-cert-chain'
    ],
    DISALLOWED_PREFIXES: ['x-amz-cf-', 'x-edge-'],
    /**
     * Read-only per event: functions can read them but can't add, modify, or delete them (502).
     * Source: "Restrictions on all edge functions › Read-only headers".
     */
    READ_ONLY: {
        'viewer-request': ['cdn-loop', 'content-length', 'host', 'transfer-encoding', 'via'],
        'origin-request': [
            'accept-encoding', 'cdn-loop', 'content-length', 'if-modified-since', 'if-none-match',
            'if-range', 'if-unmodified-since', 'transfer-encoding', 'via'
        ],
        'origin-response': ['transfer-encoding', 'via'],
        'viewer-response': ['warning', 'via']
    },
    // Additionally read-only in viewer response events for Lambda@Edge
    LAMBDA_VIEWER_RESPONSE_READ_ONLY: ['content-length', 'content-encoding', 'transfer-encoding'],
    // "If a viewer request function adds the CloudFront-Viewer-Country header, it fails validation" (502)
    VIEWER_REQUEST_CANNOT_ADD: ['cloudfront-viewer-country'],
    /**
     * Headers CloudFront adds to the request, when a cache or origin request policy asks for them.
     * Source: "Add CloudFront request headers". CloudFront adds them after the viewer request event:
     * Lambda@Edge sees them only in origin request and origin response ("Restrictions on Lambda@Edge ›
     * CloudFront headers"); CloudFront Functions have access to them ("Differences between CloudFront
     * Functions and Lambda@Edge › Access to geolocation and device data").
     */
    CLOUDFRONT_ADDED: [
        // Device type
        'cloudfront-is-android-viewer', 'cloudfront-is-desktop-viewer', 'cloudfront-is-ios-viewer',
        'cloudfront-is-mobile-viewer', 'cloudfront-is-smarttv-viewer', 'cloudfront-is-tablet-viewer',
        // Viewer location
        'cloudfront-viewer-address', 'cloudfront-viewer-asn', 'cloudfront-viewer-country', 'cloudfront-viewer-city',
        'cloudfront-viewer-country-name', 'cloudfront-viewer-country-region', 'cloudfront-viewer-country-region-name',
        'cloudfront-viewer-latitude', 'cloudfront-viewer-longitude', 'cloudfront-viewer-metro-code',
        'cloudfront-viewer-postal-code', 'cloudfront-viewer-time-zone',
        // Viewer header structure
        'cloudfront-viewer-header-order', 'cloudfront-viewer-header-count',
        // TLS
        'cloudfront-viewer-ja3-fingerprint', 'cloudfront-viewer-ja4-fingerprint', 'cloudfront-viewer-tls',
        // Other
        'cloudfront-error-uri', 'cloudfront-error-args', 'cloudfront-forwarded-proto', 'cloudfront-viewer-http-version'
    ],

    /** @deprecated Superseded by DISALLOWED / READ_ONLY; kept for programmatic API compatibility. */
    FORBIDDEN: [
        'connection', 'expect', 'keep-alive', 'proxy-authenticate',
        'proxy-authorization', 'te', 'trailer', 'transfer-encoding', 'upgrade',
        'via'
    ],
    /** @deprecated Superseded by READ_ONLY['viewer-request']. */
    REQUEST_ONLY_FORBIDDEN: [
        'host'
    ]
} as const;

/**
 * Sandbox & Runtime Configurations
 */
export const AWS_RUNTIME = {
    // Lambda@Edge has no module restrictions: "network access" and "file system access" in every event
    // ("Differences between CloudFront Functions and Lambda@Edge"). See src/core/lambda/sandbox.ts.
    DEFAULT_NODE_RUNTIME: 'nodejs22.x',
    DEFAULT_ENV: {
        'AWS_REGION': 'us-east-1',
        'AWS_DEFAULT_REGION': 'us-east-1',
        'AWS_EXECUTION_ENV': 'AWS_Lambda_nodejs22.x',
        'AWS_LAMBDA_FUNCTION_NAME': 'cloudfrontize-emulator',
        'AWS_LAMBDA_FUNCTION_VERSION': '1',
        'AWS_LAMBDA_FUNCTION_MEMORY_SIZE': '128'
    },
    ENV_WHITELIST: [
        'AWS_REGION', 'AWS_DEFAULT_REGION', 'AWS_LAMBDA_FUNCTION_NAME',
        'AWS_LAMBDA_FUNCTION_VERSION', 'AWS_LAMBDA_FUNCTION_MEMORY_SIZE',
        'AWS_LAMBDA_LOG_GROUP_NAME', 'AWS_LAMBDA_LOG_STREAM_NAME',
        'AWS_EXECUTION_ENV', 'AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'AWS_SESSION_TOKEN',
        'NODE_OPTIONS', 'TZ', 'LANG', 'PATH'
    ]
} as const;

export const CFF_RUNTIME = {
    // Strictly NO built-ins for CFF
    ALLOWED_GLOBAL: [], 
    FORBIDDEN_MODULES: ['*'] // Any require() will throw
} as const;

export const RESTRICTED_AWS_ENV = [
    'AWS_ACCOUNT_ID', 'AWS_LAMBDA_FUNCTION_NAME', 'AWS_LAMBDA_FUNCTION_VERSION',
    'AWS_LAMBDA_FUNCTION_MEMORY_SIZE', 'AWS_EXECUTION_ENV'
] as const;
